Add missing dependency
Before this commit, the app crashed with
java.lang.NoClassDefFoundError:
org/springframework/security/web/firewall/RequestRejectedHandler

[#173979424]

Co-authored-by: David Ansari <dansari@pivotal.io>